import { CreateSchoolDto } from './dto/create-school.dto';
import { UpdateSchoolDto } from './dto/update-school.dto';
import { PrismaService } from '../prisma/prisma.service';
export declare class SchoolsService {
    private prisma;
    constructor(prisma: PrismaService);
    create(createSchoolDto: CreateSchoolDto): Promise<{
        name: string;
        id: string;
        email: string | null;
        phone: string | null;
        createdAt: Date;
        updatedAt: Date;
        licenseKey: string | null;
        logo: string | null;
        slogan: string | null;
        address: string | null;
        website: string | null;
        primaryColor: string | null;
        theme: string;
        defaultLanguage: string;
        licenseExpiresAt: Date | null;
        isActive: boolean;
    }>;
    findAll(): Promise<{
        name: string;
        id: string;
        email: string | null;
        phone: string | null;
        createdAt: Date;
        updatedAt: Date;
        licenseKey: string | null;
        logo: string | null;
        slogan: string | null;
        address: string | null;
        website: string | null;
        primaryColor: string | null;
        theme: string;
        defaultLanguage: string;
        licenseExpiresAt: Date | null;
        isActive: boolean;
    }[]>;
    findPublic(): Promise<{
        name: string;
        id: string;
        logo: string | null;
        slogan: string | null;
        isActive: boolean;
    }[]>;
    findOne(id: string): Promise<{
        name: string;
        id: string;
        email: string | null;
        phone: string | null;
        createdAt: Date;
        updatedAt: Date;
        licenseKey: string | null;
        logo: string | null;
        slogan: string | null;
        address: string | null;
        website: string | null;
        primaryColor: string | null;
        theme: string;
        defaultLanguage: string;
        licenseExpiresAt: Date | null;
        isActive: boolean;
    }>;
    update(id: string, updateSchoolDto: UpdateSchoolDto): Promise<{
        name: string;
        id: string;
        email: string | null;
        phone: string | null;
        createdAt: Date;
        updatedAt: Date;
        licenseKey: string | null;
        logo: string | null;
        slogan: string | null;
        address: string | null;
        website: string | null;
        primaryColor: string | null;
        theme: string;
        defaultLanguage: string;
        licenseExpiresAt: Date | null;
        isActive: boolean;
    }>;
    toggleActive(id: string): Promise<{
        name: string;
        id: string;
        email: string | null;
        phone: string | null;
        createdAt: Date;
        updatedAt: Date;
        licenseKey: string | null;
        logo: string | null;
        slogan: string | null;
        address: string | null;
        website: string | null;
        primaryColor: string | null;
        theme: string;
        defaultLanguage: string;
        licenseExpiresAt: Date | null;
        isActive: boolean;
    }>;
    generateLicense(days: number, userId: string): Promise<{
        id: string;
        schoolId: string | null;
        createdAt: Date;
        days: number;
        code: string;
        isUsed: boolean;
        usedById: string | null;
        usedAt: Date | null;
        createdBy: string | null;
    }>;
    getAllLicenses(): Promise<{
        id: string;
        schoolId: string | null;
        createdAt: Date;
        days: number;
        code: string;
        isUsed: boolean;
        usedById: string | null;
        usedAt: Date | null;
        createdBy: string | null;
    }[]>;
    activateLicense(id: string, licenseKey: string, userId: string): Promise<{
        name: string;
        id: string;
        email: string | null;
        phone: string | null;
        createdAt: Date;
        updatedAt: Date;
        licenseKey: string | null;
        logo: string | null;
        slogan: string | null;
        address: string | null;
        website: string | null;
        primaryColor: string | null;
        theme: string;
        defaultLanguage: string;
        licenseExpiresAt: Date | null;
        isActive: boolean;
    }>;
}
