import { SchoolsService } from './schools.service';
import { CreateSchoolDto } from './dto/create-school.dto';
import { UpdateSchoolDto } from './dto/update-school.dto';
export declare class SchoolsController {
    private readonly schoolsService;
    constructor(schoolsService: SchoolsService);
    findPublic(): Promise<{
        name: string;
        id: string;
        logo: string | null;
        slogan: string | null;
        isActive: boolean;
    }[]>;
    create(createSchoolDto: CreateSchoolDto): Promise<{
        name: string;
        id: string;
        email: string | null;
        phone: string | null;
        createdAt: Date;
        updatedAt: Date;
        licenseKey: string | null;
        logo: string | null;
        slogan: string | null;
        address: string | null;
        website: string | null;
        primaryColor: string | null;
        theme: string;
        defaultLanguage: string;
        licenseExpiresAt: Date | null;
        isActive: boolean;
    }>;
    generateLicense(days: number, req: any): Promise<{
        success: boolean;
        voucher: {
            id: string;
            schoolId: string | null;
            createdAt: Date;
            days: number;
            code: string;
            isUsed: boolean;
            usedById: string | null;
            usedAt: Date | null;
            createdBy: string | null;
        };
    }>;
    getLicenses(): Promise<{
        id: string;
        schoolId: string | null;
        createdAt: Date;
        days: number;
        code: string;
        isUsed: boolean;
        usedById: string | null;
        usedAt: Date | null;
        createdBy: string | null;
    }[]>;
    findAll(): Promise<{
        name: string;
        id: string;
        email: string | null;
        phone: string | null;
        createdAt: Date;
        updatedAt: Date;
        licenseKey: string | null;
        logo: string | null;
        slogan: string | null;
        address: string | null;
        website: string | null;
        primaryColor: string | null;
        theme: string;
        defaultLanguage: string;
        licenseExpiresAt: Date | null;
        isActive: boolean;
    }[]>;
    findOne(id: string): Promise<{
        name: string;
        id: string;
        email: string | null;
        phone: string | null;
        createdAt: Date;
        updatedAt: Date;
        licenseKey: string | null;
        logo: string | null;
        slogan: string | null;
        address: string | null;
        website: string | null;
        primaryColor: string | null;
        theme: string;
        defaultLanguage: string;
        licenseExpiresAt: Date | null;
        isActive: boolean;
    }>;
    update(id: string, updateSchoolDto: UpdateSchoolDto): Promise<{
        name: string;
        id: string;
        email: string | null;
        phone: string | null;
        createdAt: Date;
        updatedAt: Date;
        licenseKey: string | null;
        logo: string | null;
        slogan: string | null;
        address: string | null;
        website: string | null;
        primaryColor: string | null;
        theme: string;
        defaultLanguage: string;
        licenseExpiresAt: Date | null;
        isActive: boolean;
    }>;
    toggleActive(id: string): Promise<{
        name: string;
        id: string;
        email: string | null;
        phone: string | null;
        createdAt: Date;
        updatedAt: Date;
        licenseKey: string | null;
        logo: string | null;
        slogan: string | null;
        address: string | null;
        website: string | null;
        primaryColor: string | null;
        theme: string;
        defaultLanguage: string;
        licenseExpiresAt: Date | null;
        isActive: boolean;
    }>;
    activateLicense(id: string, licenseKey: string, req: any): Promise<{
        success: boolean;
        school: {
            name: string;
            id: string;
            email: string | null;
            phone: string | null;
            createdAt: Date;
            updatedAt: Date;
            licenseKey: string | null;
            logo: string | null;
            slogan: string | null;
            address: string | null;
            website: string | null;
            primaryColor: string | null;
            theme: string;
            defaultLanguage: string;
            licenseExpiresAt: Date | null;
            isActive: boolean;
        };
        message?: undefined;
    } | {
        success: boolean;
        message: any;
        school?: undefined;
    }>;
}
